### ISSUE TITLE
Weird Icons showing in the carrousel

### ISSUE THREAD

**Issue by aflibottesavoie** [death-save/combat-carousel#81] opened 2021-07-15 17:35 UTC
I'm unsure if this is a bug, but I think it might be since I am not finding any ways of disabling these Icons. The Icons at the bottom of the character cards are filling up a decent chunk of some of my characters and I would like for them to not show. 

The Icons are always displayed and seem to be related to some of the character's feat / features which is really strange. I have not found a way to disable them.

![image](https://user-images.githubusercontent.com/6451770/125831793-179b47c3-ff6c-4530-969e-0ac2553f14a3.png)

**To Reproduce**
This is always present for my tokens in any combat

**Expected behavior**
A way to disable these Icons

**Environment Info (please complete the following information):**
I'm using Pathfinder2e as a system (2.9.1.6656).
Happens locally and online

**Comment by eclarke12** [comment] 2021-07-15 17:42
duplicate of #73

**Closed by eclarke12** 2021-07-15 17:42 UTC
Labels: bug, duplicate
