### ISSUE TITLE
Consider changing the behaviour of card hover

### ISSUE THREAD

**Issue by gitmon1234** [death-save/combat-carousel#63] opened 2021-04-21 22:03 UTC
**Describe the bug**
When you hover over the red d20 icon in the carousel to roll initiative for a creature, the entire card enlarges. This brings the "remove from encounter" button directly under the cursor position. This make it easy to misclick and remove a creature from the encounter instead of rolling initiative, especially if there is any visual lag in the scene.

**To Reproduce**
When logged in as gamemaster, move the cursor to the center of the red d20 icon in the upper right of any card in the carousel.
Left click.

**Expected behavior**
UI buttons should not change position when the mouse moves over them. 
Suggest adjusting the resizing behavior so that the name/utility bar for each creature is always present in the same location at the top of the carousel, and only the image card is resized when hovered. This would keep the initiative button from jumping

**Desktop (please complete the following information):**
Combat Carousel v. 0.1.3
Foundry v. 0.7.9

**Comment by eclarke12** [comment] 2021-07-07 04:51
duplicate of #24

**Closed by eclarke12** 2021-07-07 04:51 UTC
Labels: duplicate, enhancement
