### ISSUE TITLE
Combat Carousel missing start combat button.

### ISSUE THREAD

**Issue by SirAron111** [death-save/combat-carousel#150] opened 2022-10-08 12:38 UTC
**Describe the bug**
Since V10 i have a problem that the combat no longer starts when i press the next turn button/the button doesn't show up sometimes at all till i manually start the combat in the combat tab of foundry.

**To Reproduce**
1. Select a bunch of tokens.
2. Click the sword and shield icon to add them to initiative.
3. roll for initiatives.
4. try to start combat by pressing the arrow button on the bottom right.
5. See that it only switches to the next turn, but doesn't actually start combat.

**Expected behavior**
well it should start combat or at least have a dedicated start combat button in its UI if the arrow icons stopped working for that.

**Environment Info (please complete the following information):**
 - Foundry Version: [e.g. v10 build287]
 - Game System / Version: [e.g. dnd5e 2.0.3]
 - CC Version [e.g. 0.3.0]
 - Browser [e.g. all and in the application itself]
 - OS [e.g. Windows 10]

**Comment by eclarke12** [comment] 2022-10-09 03:14
Duplicate of #142

**Closed by eclarke12** 2022-10-09 03:14 UTC
Labels: bug
