### ISSUE TITLE
Overlay Turn Marker Not Working With Combat Carousel

### ISSUE THREAD

**Issue by bearsy1** [death-save/combat-carousel#148] opened 2022-09-08 01:04 UTC
**Describe the bug**
The animated turn markers of other modules (tested with [Monk's Little Details](https://github.com/ironmonk88/monks-little-details) combat tracker and with [Combat Booster's](https://github.com/theripper93/Combat-Booster) turn marker) do not render/show on tokens on the canvas during combat when used with CC being active.

**To Reproduce**
1. Activate Combat Booster with the Turn Marker option enabled. Do not have Combat Carousel activated in 'manage module' settings.
2. Start a combat encounter with at least one token/player/npc and verify that the turn marker overlay is working and showing the current combatant as intended. End combat.
3. Enable Combat Carousel in 'manage module' settings.
4. Start a combat encounter with at least one token/player/npc and note that the turn marker overlay is no longer working.

**Expected behavior**
Users should be able to see the current player's/npc's token highlighted by a revolving/spinning/animated overlay alongside with being able to see and use the combat carousel with all of its features during a combat encounter.

**Screenshots**
N/A (screenshots would simply by of tokens with and without the turn marker overlays)

**Environment Info (please complete the following information):**
 - Foundry Version:  10.284
 - Game System / Version: DnD5e 2.0.2
 - CC Version: 0.3.0
 - Browser: Firefox 104.0.2
 - OS: Windows 11

**Additional context**
Deactivated all other modules when testing to make sure it was something caused by the interaction of combat carousel and the modules that add overlays to tokens during combat. Also logged a bug report with at least Combat Booster in case it is something caused by that module instead.

**Comment by theripper93** [comment] 2022-09-08 12:16
i'll close the issue on my repo and follow here to avoid duplication on discussions, but i cannot reproduce this issue, the only difference i can se in our setups is that i'm using windows 10 and the electron client
![image](https://user-images.githubusercontent.com/1346839/189119408-1e802867-af7c-4847-815f-917a9954dd9b.png)

**Comment by theripper93** [comment] 2022-09-08 12:18
Logged in as player with firefox, still working
![image](https://user-images.githubusercontent.com/1346839/189119854-aea6b8e8-8230-4ffc-b0c7-4f48f385abec.png)

**Comment by bearsy1** [comment] 2022-09-08 23:37
); Why is it just my setup that is jank then. Thanks for looking into this though!

**Comment by eclarke12** [comment] 2022-10-19 05:20
Thanks for the investigation @theripper93 ! I will try to repro and then go from there.

**Comment by bearsy1** [comment] 2022-11-05 23:06
Not sure if this is all that helpful, but I have done the following with results to report!

- switched browsers (using Vivaldi 5.5.2805.42 stable 64-bit)
- added _way_ more modules to my foundry setup
- updated foundry/dnd5e/all modules to their latest equivalents

When I tested this again just now, I found an interesting behavior. I made a test combat encounter with a few tokens and using the carousel's UI to advance rounds (the circular button with the symbol that looks like it has a 'next track' icon), the turn overlay marker did not show upon combat / first round start. 

However, using foundry's native 'next turn' button in the side panel triggered the token combat overlay to display. Also, when I tested starting and advancing combat with macros, token overlays still worked as well.

**Comment by eclarke12** [comment] 2022-11-12 16:30
> Not sure if this is all that helpful, but I have done the following with results to report!
> 
> * switched browsers (using Vivaldi 5.5.2805.42 stable 64-bit)
> * added _way_ more modules to my foundry setup
> * updated foundry/dnd5e/all modules to their latest equivalents
> 
> When I tested this again just now, I found an interesting behavior. I made a test combat encounter with a few tokens and using the carousel's UI to advance rounds (the circular button with the symbol that looks like it has a 'next track' icon), the turn overlay marker did not show upon combat / first round start.
> 
> However, using foundry's native 'next turn' button in the side panel triggered the token combat overlay to display. Also, when I tested starting and advancing combat with macros, token overlays still worked as well, alongside combat carousel.

I've changed the way CC starts encounters in 0.3.1 so perhaps that will fix your issue when it releases.

**Closed** 2022-11-12 23:43 UTC
Labels: bug, unconfirmed
