### ISSUE TITLE
Carousel no longer works for CPR-CORE System

### ISSUE THREAD

**Issue by jerichojx** [death-save/combat-carousel#78] opened 2021-07-12 07:03 UTC
It seems the new version of Carousel no longer works with CPR Core System.

Module version: 0.2.1
Foundry version: 0.8.8
System: Cyberpunk Red Core 0.77.1
https://gitlab.com/JasonAlanTerry/fvtt-cyberpunk-red-core

**Comment by WildBillLives** [comment] 2021-07-18 21:16
I can confirm this issue with Cyberpunk Red system. The console shows the following error message:

_TypeError: An error occurred while rendering CombatCarousel 86: Cannot set property 'title' of null
    at CombatCarousel.prepareTurnData (combat-carousel.mjs:248)
    at combat-carousel.mjs:313
    at Array.map (<anonymous>)
    at CombatCarousel.getData (combat-carousel.mjs:313)
    at CombatCarousel._render (foundry.js:2042)
    at x.🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:465)
    at CombatCarousel.🎁Application.prototype._render#lib-wrapper (listeners.js:75)
    at CombatCarousel.🎁Application.prototype._render#0 (libWrapper-wrapper.js:160)
    at CombatCarousel._render (combat-carousel.mjs:48)
    at CombatCarousel.render (foundry.js:2004)_

**Comment by diwako** [comment] 2021-08-06 06:32
Encountered the same issue. Seems to be the module does not function if it is pointed to a wrong or none existing HP value.

There is an easy workaround, which is system specific, it is to link to the correct HP value object. For CPRED-Core you need to change the module settings for Bar 1 Attribute from `attributes.hp` to `derivedStats.hp`.

**Comment by eclarke12** [comment] 2021-09-01 05:10
Related to #98

**Comment by eclarke12** [comment] 2021-09-04 05:06
Fixed by #100

**Closed by eclarke12** 2021-09-04 05:06 UTC
Labels: bug
