### ISSUE TITLE
Cannot roll initiative from Carousel in pf2e

### ISSUE THREAD

**Issue by ProseBeforeHos** [death-save/combat-carousel#140] opened 2022-07-27 17:16 UTC
**Describe the bug**
When using CC with PF2e, you cannot roll inti by simply clicking the dice.

**To Reproduce**
Just attempt to click the button... it will not work. 

**Expected behavior**
The token represented on the combat tracked would roll init.

**Screenshots**
https://snipboard.io/xVsb1p.jpg

**Environment Info (please complete the following information):**
 - Foundry Version: 9 269
 - Game System / Version: PF2e 3.12.2.10
 - CC Version: I got no idea...
 - Browser: Brave.
 - OS Windows 10

**Additional context**
n/a

**Comment by eclarke12** [comment] 2022-08-14 04:12
Duplicate of #127

**Closed by eclarke12** 2022-08-14 04:12 UTC
Labels: bug, duplicate, external
